"""add user profile and gemini fields

Revision ID: 98bd22453b63
Revises: 
Create Date: 2026-02-18 11:40:50.676550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98bd22453b63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('risk_tolerance', sa.Enum('conservative', 'moderate', 'aggressive', name='risktolerance'), nullable=True))
    op.add_column('user', sa.Column('investment_horizon_years', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('monthly_income', sa.Numeric(), nullable=True))
    op.add_column('user', sa.Column('gemini_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gemini_api_key')
    op.drop_column('user', 'monthly_income')
    op.drop_column('user', 'investment_horizon_years')
    op.drop_column('user', 'risk_tolerance')
    op.drop_column('user', 'date_of_birth')
    # ### end Alembic commands ###
